### ISSUE TITLE
LoggerConfiguratorPhp

### ISSUE THREAD

**Issue by hernandobgx** [floriansemm/Log4PhpBundle#1]
I have the following error when running  Log4PhpBundle:

User Warning: log4php: Specified configurator class [LoggerConfiguratorPhp]
does not exist. Reverting to default configurator. in
/var/www/kenovix/proyectos/cahis/vendor/log4php/src/main/php/Logger.php
line 547

my stack trace say:
1. at *trigger_error *('log4php: Specified configurator class
   [LoggerConfiguratorPhp] does not exist. Reverting to default
   configurator.', '512')
   in
   /var/www/kenovix/proyectos/cahis/vendor/log4php/src/main/php/Logger.php at
   line 547
2. at *Logger ::getConfigurator *('LoggerConfiguratorPhp')
   in  /var/www/kenovix/proyectos/cahis/vendor/log4php/src/main/php/Logger.php at
   line 518 
3. at _Logger ::configure *(_array_('appenders' => *array_('default' => *
   array_('class' => 'LoggerAppenderFile', 'layout' => *array_('class' =>
   'LoggerLayoutTTCC', 'params' => _array_()), 'params' => _array_('file'
   => '/var/www/kenovix/proyectos/cahis/app/logs/default.log'), 'filters' =>
   _array_(), 'threshold' => _null_)), 'rootLogger' => _array_('level' =>
   'DEBUG', 'appenders' => _array_('default')), 'renderers' => _array_(),
   'threshold' => _null_, 'loggers' => _array_()), 'LoggerConfiguratorPhp')
   in  /var/www/kenovix/proyectos/cahis/vendor/bundles/FS/Log4PhpBundle/Logger.php
   at line 36
4. at _Logger ->configureLogger *(_array_('appenders' => *array_('default'
   => _array_('class' => 'LoggerAppenderFile', 'layout' => _array_('class'
   => 'LoggerLayoutTTCC', 'params' => _array_()), 'params' => _array_('file'
   => '/var/www/kenovix/proyectos/cahis/app/logs/default.log'), 'filters' =>
   _array_(), 'threshold' => _null_)), 'rootLogger' => _array_('level' =>
   'DEBUG', 'appenders' => _array_('default')), 'renderers' => _array_(),
   'threshold' => _null_, 'loggers' => _array_()))
   in kernel.root_dir/cache/dev/appDevDebugProjectContainer.php at line
   924 

you could guide me in this regard. Excuse me for my English

thanks!!!

**Comment by floriansemm** [comment]
There are some changes in the API of Log4Php. I have implemented the bundle with an older version of Log4Php. 

I will update my local version and fix this.

**Comment by hernandobgx** [comment]
thank you very much I am very aware of this update again thanks for your help

**Comment by floriansemm** [comment]
should be fixed

**Comment by floriansemm** [comment]
i push my changes into the master this evening
